project:
  type: website
  output-dir: docs
   


website:
  search: false
  title: "Brenda Cruz"
  navbar:
    collapse: true
    left:
      - href: about.qmd
        text: "About Me"
      - href: myblog.qmd
        text: "My Notes"
    right: 
      - icon: github
        href: https://github.com/bscruz

format:
  html:
    theme: 
      - theme.scss
    toc: true

editor: visual

